<?php

declare(strict_types=1);

use App\Enums\RedirectType;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Requirement 7.5.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('redirects', function (Blueprint $table): void {
            $table->id();

            /*
             * Path only, not a full URL, and always leading-slashed. Storing
             * hosts would make redirects break the moment a site moves domain or
             * runs on a staging hostname.
             *
             * Length 191 rather than the default 255: this column is uniquely
             * indexed, and on MySQL with utf8mb4 a 255-char unique index exceeds
             * the 767-byte limit on older InnoDB row formats. 191 * 4 = 764.
             */
            $table->string('from_path', 191)->unique();
            $table->string('to_path');

            $table->unsignedSmallInteger('type')->default(RedirectType::Permanent->value);

            // Hit counter makes dead redirects visible, so the table can be
            // pruned on evidence rather than guesswork.
            $table->unsignedBigInteger('hits')->default(0);
            $table->timestamp('last_hit_at')->nullable();

            /*
             * Set when the redirect was generated by a slug change, so the panel
             * can distinguish automatic entries from hand-written ones.
             */
            $table->nullableMorphs('source');
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();

            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('redirects');
    }
};
